**# 数组的创建和计算**

**1. 数组的基本属性**

In [11]:
import numpy as np

a = np.array([1,2,3])   # 创建一维数组，即向量
a, type(a), a.dtype     # 生成数组，数组的类名，数组的类型

(array([1, 2, 3]), numpy.ndarray, dtype('int64'))

In [12]:
a.size, a.shape  # 数组的大小(包含元素个数)，数组的形状

(3, (3,))

In [13]:
b = np.array([[1,2,3], [4,5,6]])  # 创建二维数组，即矩阵
b, b.shape, b.size

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3), 6)

In [14]:
c = np.array(1)  # 创建0维数组，即标量
c, c.shape, c.size

(array(1), (), 1)

In [15]:
a = np.array([1,2,3],dtype = np.float32)  # 指定数组的类型 
a

array([1., 2., 3.], dtype=float32)

In [16]:
b = np.array([0.0123,0.0456,0.0789,0.0321])  # 保留浮点数的小数位数
np.round(b,2)

array([0.01, 0.05, 0.08, 0.03])

In [17]:
a.astype(np.int8) # 修改数组的类型

array([1, 2, 3], dtype=int8)

* 数组的其他创建方法

In [18]:
b = np.array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c = np.arange(10)  # 等价于 np.array(range()) 方法
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
d = np.arange(4,10,2)
d

array([4, 6, 8])

* 数组形状的修改

In [21]:
A = np.arange(24).reshape(2,2,6) # 创建一个三维数组
A

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [22]:
A.reshape(3,2,4)  # 表示3个矩阵，每个矩阵是2 x 4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
A.shape  # reshape 不会改变数组本身的形状

(2, 2, 6)

In [24]:
A.reshape(24,)  # 一维数组，一维行向量的形式，但是在计算中是按列向量进行计算的

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
A.reshape(24,1)  # 矩阵的列向量展示

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [26]:
A.reshape(1,24) # 矩阵的行向量展示

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
A, A.flatten()  # 将数组展开成一维形式

(array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]))

**2. 数组的计算**

In [28]:
x = np.arange(12).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

* 数组与标量的计算

In [29]:
# 标量和每一个元素进行加减乘除运算
x + 2

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [30]:
x * 2

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[12, 14, 16],
        [18, 20, 22]]])

* 数组与数组的计算

In [31]:
y = np.array([[[1,1,1],[1,1,1]], [[2,2,2],[2,2,2]]])
y

array([[[1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [32]:
# 加减乘除表示的是，对应元素的运算
x + y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [33]:
x * y

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [34]:
# 广播机制
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [35]:
B = np.ones((4,6), dtype = np.int32)
B

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [36]:
A + B # 即 A 会自动填充至和 B 相同的形状之后进行运算

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

**2.1 np.dot()**

* **向量内积**

In [37]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([2, 3, 4, 5, 6, 7, 8])

np.dot(x, y)

168

In [38]:
# 等价于向量的对应元素乘法，然后求和
(x*y).sum()

168

In [39]:
x.shape, y.shape

((7,), (7,))

* **矩阵乘法**

In [40]:
x = np.array([[1, 2, 3],
              [3, 4, 4]])
y = np.array([[0, 1, 1, 1],
              [1, 2, 0, 1],
              [0, 0, 2, 1]])

np.dot(x, y)

array([[ 2,  5,  7,  6],
       [ 4, 11, 11, 11]])

In [41]:
x.shape, y.shape, np.dot(x, y).shape

((2, 3), (3, 4), (2, 4))

* **矩阵向量乘法**

In [42]:
x = np.array([[1, 2, 3],
              [3, 4, 4]])
y = np.array([1, 2, 3])

np.dot(x, y)

array([14, 23])

In [43]:
x.shape, y.shape

((2, 3), (3,))

**2.2 np.power()**

* np.power( )用于数组元素求n次方

In [44]:
x1 = 2
x2 = 3
np.power(x1,x2)

# x1和x2可以是整数类型或数组或者array类型，x1和x2的列数要相同

8

In [45]:
x1 = np.array([[0,1],[2,3]])
x2 = np.array([[3,4],[4,5]])
np.power(x1,x2) 

# 相应位置的前者的后者次方(x1[i,j]**x2[i,j])

array([[  0,   1],
       [ 16, 243]])

**2.3 转置**

In [48]:
x = np.arange(18).reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [50]:
x.T

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [51]:
x.transpose()

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [52]:
x.swapaxes(1,0)

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])