**# 数组的创建和计算**

* 数组的基本属性

In [34]:
import numpy as np

a = np.array([1,2,3])   # 创建一维数组，即向量
a, type(a), a.dtype     # 生成数组，数组的类名，数组的类型

(array([1, 2, 3]), numpy.ndarray, dtype('int64'))

In [35]:
a.size, a.shape  # 数组的大小(包含元素个数)，数组的形状

(3, (3,))

In [45]:
b = np.array([[1,2,3], [4,5,6]])  # 创建二维数组，即矩阵
b, b.shape, b.size

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3), 6)

In [37]:
c = np.array(1)  # 创建0维数组，即标量
c, c.shape, c.size

(array(1), (), 1)

In [38]:
a = np.array([1,2,3],dtype = np.float32)  # 指定数组的类型 
a

array([1., 2., 3.], dtype=float32)

In [39]:
b = np.array([0.0123,0.0456,0.0789,0.0321])  # 保留浮点数的小数位数
np.round(b,2)

array([0.01, 0.05, 0.08, 0.03])

In [40]:
a.astype(np.int8) # 修改数组的类型

array([1, 2, 3], dtype=int8)

* 数组的其他创建方法

In [41]:
b = np.array(range(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
c = np.arange(10)  # 等价于 np.array(range()) 方法
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
d = np.arange(4,10,2)
d

array([4, 6, 8])

* 数组形状的修改

In [48]:
A = np.arange(24).reshape(2,2,6) # 创建一个三维数组
A

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [49]:
A.reshape(3,2,4)  # 表示3个矩阵，每个矩阵是2 x 4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
A.shape  # reshape 不会改变数组本身的形状

(2, 2, 6)

In [50]:
A.reshape(24,)  # 一维数组，一维行向量的形式，但是在计算中是按列向量进行计算的

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [51]:
A.reshape(24,1)  # 矩阵的列向量展示

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [52]:
A.reshape(1,24) # 矩阵的行向量展示

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [54]:
A, A.flatten()  # 将数组展开成一维形式

(array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]))

* 数组的计算

In [82]:
x = np.arange(12).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [77]:
# 数组与标量的计算，标量和每一个元素进行加减乘除运算
x + 2

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [79]:
x * 2

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [86]:
# 数组与数组的计算，
y = np.array([[[1,1,1],[1,1,1]], [[2,2,2],[2,2,2]]])
y

array([[[1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [81]:
# 加减乘除表示的是，对应元素的运算
x + y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [84]:
x * y

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [87]:
# 广播机制
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [92]:
B = np.ones((4,6), dtype = np.int32)
B

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [93]:
A + B # 即 A 会自动填充至和 B 相同的形状之后进行运算

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])