**# numpy索引和切片**

**读取行/列**

In [3]:
import numpy as np

a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
# 读取行
a[1,:], a[1] 

(array([ 6,  7,  8,  9, 10, 11]), array([ 6,  7,  8,  9, 10, 11]))

In [ ]:
# 读取列
a[:,1]

array([ 1,  7, 13, 19, 25, 31])

In [ ]:
# 读取连续多行
a[1:3]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
# 读取不连续多行
a[[0,1,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
# 读取多列
a[:,1:3]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [ ]:
# 读取不连续多列
a[:,[1,3,5]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [ ]:
# 读取单行单列，即单个点
a[2,3]

15

In [ ]:
# 读取多行多列，第3行到第5行，第2列到第4列
a[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [ ]:
# 取多个点
a[[0,2,4],[0,1,3]]   # 表示坐标为(0,0), (2,1), (4,3)的三个点

array([ 0, 13, 27])

**数值修改**

In [ ]:
# 直接赋值修改 
a[2:5,1:4] = 0
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12,  0,  0,  0, 16, 17],
       [18,  0,  0,  0, 22, 23],
       [24,  0,  0,  0, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**布尔索引**

In [11]:
# 进行判断
a = np.arange(36).reshape(6,6)

a<9

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [12]:
# 根据判断修改
a[a<9] = 1
a

array([[ 1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**三元运算符**

In [9]:
a = np.arange(36).reshape(6,6)

np.where(a<9,1,100)   # 等价于if a < 9, a = 1, else a = 100

array([[  1,   1,   1,   1,   1,   1],
       [  1,   1,   1, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [10]:
a # 不改变原始数据

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**clip(裁剪)**

In [6]:
a = np.arange(36).reshape(6,6)
a.clip(10,18)  

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18, 18]])

In [7]:
a # 不改变原始数据

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**数据类型**

In [13]:
a[3,3] = np.nan

ValueError: ignored

In [17]:
a.astype(float)
a[3,3] = np.nan
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., nan, 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])